# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="LEADER"
DIST_VERSION="0.39"


inherit perl-module

DESCRIPTION="Let's Encrypt API interfacing module and client."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND=">=dev-perl/Crypt-OpenSSL-Bignum-0.90.0
	>=dev-perl/Net-SSLeay-1.940.0
	>=dev-perl/Crypt-OpenSSL-RSA-0.350.0
	dev-perl/JSON-MaybeXS
	>=dev-perl/Convert-ASN1-0.340.0
	>=dev-perl/IO-Socket-SSL-2.95.0
	>=dev-perl/Log-Log4perl-1.570.0
	dev-perl/Module-Build
	dev-lang/perl"
