# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.9

EAPI=7

MODULE_AUTHOR="LEADER"
MODULE_VERSION="0.38"
inherit perl-module

DESCRIPTION="Let's Encrypt API interfacing module and client."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
SRC_URI="mirror://cpan/${DIST_A}"

KEYWORDS="amd64"
IUSE=""

DEPEND=">=dev-perl/Crypt-OpenSSL-RSA-0.320.0
	>=dev-perl/Crypt-OpenSSL-Bignum-0.90.0
	>=dev-perl/IO-Socket-SSL-2.74.0
	>=dev-perl/Log-Log4perl-1.540.0
	dev-perl/Module-Build
	>=dev-perl/Convert-ASN1-0.330.0
	dev-perl/JSON-MaybeXS
	>=dev-perl/Net-SSLeay-1.920.0
	dev-lang/perl"
